' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [AutoController]
  [AutoResolver]

  [AutoService]

  [Repository<Auto>]
}


cloud {
    [TypeORM]
}

database "DB auto" {
    [Tabelle auto]
    [Tabelle fahrzeugklasse]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [AutoController]
[RequestLoggerMiddleware] ~~> [AutoResolver]

[AutoController] ..> [AutoService]
[AutoResolver] ..> [AutoService]
[AutoService] ..> [Repository<Auto>]

[Repository<Auto>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle auto]
[TypeORM] ~~> [Tabelle fahrzeugklasse]

@enduml
